name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/studentPantry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build, Test, and Generate Report with Maven
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Upload Surefire Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: backend/studentPantry/target/site/surefire-report.html
          if-no-files-found: error

      - name: Send Test Report via Email
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 587
          smtp-username: soumyavaidya09@gamil.com
          smtp-password: "icej ttwt mhtg zoxn"
          from: soumyavaidya09@gamil.com
          to: soumyasv@umich.edu
          subject: "Test Report"
          body: "Please find the attached test report."
          attachments: backend/studentPantry/target/site/surefire-report.html
