name: Angular CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/pantry-pal-frontend-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/pantry-pal-frontend-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: npm run build --if-present

      - name: Run unit tests with coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable

      - name: Upload code coverage report to GitHub (optional)
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/*.json  
